<a href="https://colab.research.google.com/github/kumarpraveengmail/kumarpraveengmail/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy 1st**

In [ ]:
python_list = [1,2,3,4,5,6,7,8]
print(python_list)

import numpy as np
numpy_array = np.array(python_list)
print(numpy_array)


[1, 2, 3, 4, 5, 6, 7, 8]
[1 2 3 4 5 6 7 8]


# **1D Array**

In [ ]:
import numpy as np
ar_1d = np.array([1,2,3,4,5])
print(ar_1d)

[1 2 3 4 5]


# **2D Array**


In [ ]:
# 2D Array
import numpy as np
ar_2d = np.array([[1,2,3],[4,5,6]])
print(ar_2d)

[[1 2 3]
 [4 5 6]]


# **Multi-dimensional array**

In [ ]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(matrix)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
#Zero
import numpy as np
ar_zero = np.zeros((2,3))
print(ar_zero)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#Ones
import numpy as np
ar_ones = np.ones((2,3))
print(ar_ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#Full Shape
import numpy as np
ar_full = np.full((2,3),5)
print(ar_full)

[[5 5 5]
 [5 5 5]]


In [ ]:
# Creating Sequnce of Number in numpy
import numpy as np
ar_seq = np.arange(1,10,2)
print(ar_seq)

[1 3 5 7 9]


In [ ]:
# Creating identity matrices
import numpy as np
ar_identity = np.eye(4)
print(ar_identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# Shape
import numpy as np
ar_shape  = np.array([[1,2,3],[4,5,6]])
ar_shape.shape


(2, 3)

In [ ]:
# Size
import numpy as np
ar_size = np.array([[10,20,30],[4,5,6]])
ar_size.size

6

In [ ]:
# ndim
import numpy as np
new_var = 2
ar_1d = np.array([1,new_var,3])
ar_2d = np.array([[1,2,3],[4,5,6]])
ar_3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(ar_1d.ndim)
print(ar_2d.ndim)
print(ar_3d.ndim)

1
2
3


In [ ]:
# dtype

import numpy as np
ar_dtype1 = np.array([1,2,3,4,9])
ar_dtype2 = np.array([1.1,2.2,3.3,4.4])
ar_dtype3 = np.array(["a","b","c","d"])

print(ar_dtype.dtype)
print(ar_dtype2.dtype)
print(ar_dtype3.dtype)

int64
float64
<U1


In [ ]:
# astype
import numpy as np
ar_dtyp = np.array([1.1,2.2,3.3,4.4])
int_array = ar_dtyp.astype(int)
print(ar_dtyp.dtype)
print(int_array.dtype)

float64
int64


In [ ]:
# mathmatices
arr = np.array([10,30,20])

print(arr+5)
print(arr-5)
print(arr*5)
print(arr/5)
print(arr%5)
print(arr**5)

[15 35 25]
[ 5 25 15]
[ 50 150 100]
[2. 6. 4.]
[0 0 0]
[  100000 24300000  3200000]


In [ ]:
#  Agg_func
import numpy as np
arr = np.array([23,12,43,54,12,66,1,32,7,3,6,4,8,54,34,22,12,13,14,19])
print('min ',np.min(arr))
print('max ',np.max(arr))
print('mean ',np.mean(arr))
print('median ',np.median(arr))
print('std ',np.std(arr))
print('var ',np.var(arr))
print('sum ',np.sum(arr))
print('prod ',np.prod(arr))
print('sum ',sum(arr))

min  1
max  66
mean  21.95
median  13.5
std  18.61041375144572
var  346.34749999999997
sum  439
prod  8058576634413842432
sum  439


In [ ]:
import  numpy as np
arr = np.array([23,12,43,54,12,66,1,32,7,3,6,4,8,54,34,22,12,13,14,19])
print(arr[1:5]) # index  1 to 4
print(arr[:4]) # index 0 to 4
print(arr[::2]) # every second element
print(arr[::-1]) # reverse

[12 43 54 12]
[23 12 43 54]
[23 43 12  1  7  6  8 34 12 14]
[19 14 13 12 22 34 54  8  4  6  3  7 32  1 66 12 54 43 12 23]


In [ ]:
import numpy as np
arr = np.array([23,12,43,54,12,66,1,32,7,3,6,4,8,54,34,22,12,13,14,19])
print(arr[[0,2,4]])

[23 43 12]


In [ ]:
# Reshaping and manipulating
import numpy as np
arr = np.array([23,12,43,54,12,66,1,32,7,3,6,4,8,54,34,22,12,13,14,19])
print(arr)
print(arr.shape)
print(len(arr))
arr_reshape = arr.reshape(4,5)
print(arr_reshape)
print(arr_reshape.shape)
print(len(arr_reshape))

[23 12 43 54 12 66  1 32  7  3  6  4  8 54 34 22 12 13 14 19]
(20,)
20
[[23 12 43 54 12]
 [66  1 32  7  3]
 [ 6  4  8 54 34]
 [22 12 13 14 19]]
(4, 5)
4


In [ ]:
import numpy as np
# .ravel() - value
# .flatten() - copy
arr_2d = np.array([[1,2,3],[4,5,6]]) # Convert list to NumPy array
print(arr_2d)
print(arr_2d.flatten())
print(arr_2d.ravel())

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [ ]:
""" Advanced Numpy Array
np.insert(array,index,value,asix=None)
np.delete(array,index,axis=None)
np.append(array,value,axis=None)
np.unique(array)
"""

import numpy as np

arr = np.array([23,12,43,54,12,66,1,32,7,3,6,4,8,54,34,22,12,13,14,19])
print(arr)
new_arr = np.insert(arr,2,100)
print(new_arr)

[23 12 43 54 12 66  1 32  7  3  6  4  8 54 34 22 12 13 14 19]
[ 23  12 100  43  54  12  66   1  32   7   3   6   4   8  54  34  22  12
  13  14  19]


In [ ]:
import numpy as np

arr_2d = np.array([[1,2,3],[4,5,6]]) # Convert list to NumPy array
print(arr_2d)
new_arr_2d = np.insert(arr_2d,2,[100,56],axis=1)
print(new_arr_2d)

[[1 2 3]
 [4 5 6]]
[[  1   2 100   3]
 [  4   5  56   6]]


In [1]:
"""
np.concatenet(array1,,array2),axis=None)
axis = 0 (row)
axis = 1 (column)
"""
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr3 = np.concatenate((arr1,arr2))
print(arr3)

[1 2 3 4 5 6]


In [2]:
"""
np.delete(array,index,axis=None)
flatten array
"""
import numpy as np
arr = np.array([23,12,43,54,12,66,1,32,7,3,6,4,8,54,34,22,12,13,14,19])
print(arr)
new_arr = np.delete(arr,2)
print(new_arr)

[23 12 43 54 12 66  1 32  7  3  6  4  8 54 34 22 12 13 14 19]
[23 12 54 12 66  1 32  7  3  6  4  8 54 34 22 12 13 14 19]


In [7]:
import numpy as np
arr_2d = np.array([[1,2,3],[4,5,6]]) # Convert list to NumPy array
print(arr_2d)
new_arr_2d = np.delete(arr_2d,1,axis=0)
print(new_arr_2d)

[[1 2 3]
 [4 5 6]]
[[1 2 3]]


In [10]:
# spling
# hsplit
# vsplit

import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
print(arr)
new_arr = np.array_split(arr,3)
print(new_arr)

print(new_arr[0])
print(new_arr[1])
print(new_arr[2])

print(new_arr[0][2])

[1 2 3 4 5 6 7 8]
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8])]
[1 2 3]
[4 5 6]
[7 8]
3


In [16]:
# Brodcasting
import numpy as np
prices =  [100,200,300,400,500]
discount = 10
final_prices = []
for price in prices:
  final_price = price - (price*discount/100)
  final_prices.append(final_price)

print(final_prices)


[90.0, 180.0, 270.0, 360.0, 450.0]
